# -*- coding:utf-8 -*-

ngramasToIgnore = (
    # Nexos comúns.
    u"A", u"As", u"O", u"Os", u"da", u"das", u"de", u"do", u"dos", u"e",

    # Outros termos comúns correctos en galego.
    u"Abaixo",
    u"Aldea", u"Aldeas",
    u"Alta", u"Altas", u"Alto", u"Altos",
    u"Arriba",
    u"Baixa", u"Baixas", u"Baixo", u"Baixos",
    u"Barrio", u"Barrios",
    u"Branca", u"Brancas", u"Branco", u"Brancos",
    u"Cabo",
    u"Camiño", u"Camiños",
    u"Campo", u"Campos",
    u"Casa", u"Casas",
    u"Castelo", u"Castelos",
    u"Castiñeiro", u"Castiñeiros",
    u"Castro", u"Castros",
    u"Cidade", u"Cidades",
    u"Cima", u"Cimas",
    u"Concello", u"Concellos",
    u"Confederación", u"Confederacións",
    u"Coroa", u"Coroas",
    u"Costa", u"Costas",
    u"Cruceiro", u"Cruceiros",
    u"Cruz", u"Cruces",
    u"Democrática", u"Democráticas", u"Democrático", u"Democráticos",
    u"Ducado", u"Ducados",
    u"Estado", u"Estados",
    u"Faro", u"Faros",
    u"Federación", u"Federacións",
    u"Federada", u"Federadas", u"Federado", u"Federados",
    u"Federal", u"Federais",
    u"Feira", u"Feiras",
    u"Fonte", u"Fontes",
    u"Gran", u"Grande", u"Grandes",
    u"Igrexa", u"Igrexas",
    u"Illa", u"Illas",
    u"Imperio", u"Imperios",
    u"Insua", u"Insuas",
    u"Leste",
    u"Libre", u"Libres",
    u"Lombo", u"Lombos",
    u"Lugar", u"Lugares",
    u"Monte", u"Montes",
    u"Nova", u"Novas", u"Novo", u"Novos",
    u"Norte",
    u"Occidental", u"Occidentais",
    u"Oeste",
    u"Oliveira", u"Oliveiras",
    u"Oriental", u"Orientais",
    u"Outeiro", u"Outeiros",
    u"País", u"Países",
    u"Pazo", u"Pazos",
    u"Pequena", u"Pequenas", u"Pequeno", u"Pequenos",
    u"Ponte", u"Pontes",
    u"Popular", u"Populares",
    u"Porta", u"Portas",
    u"Porto", u"Portos",
    u"Principado", u"Principados",
    u"Provincia", u"Provincias",
    u"Real", u"Reais",
    u"Regueiro", u"Regueiros",
    u"Reino", u"Reinos",
    u"República", u"Repúblicas",
    u"Ribeira", u"Ribeiras",
    u"Río", u"Ríos",
    u"Rúa", u"Rúas",
    u"San", u"Santa", u"Santas", u"Santo", u"Santos",
    u"Señorío", u"Señoríos",
    u"Silva", u"Silvas",
    u"Socialista", u"Socialistas",
    u"Sol", u"Soles",
    u"Souto", u"Soutos",
    u"Sur",
    u"Torre", u"Torres",
    u"Unida", u"Unidas", u"Unido", u"Unidos",
    u"Unión", u"Unións",
    u"Val", u"Vales",
    u"Veiga", u"Veigas",
    u"Vella", u"Vellas", u"Vello", u"Vellos",
    u"Verde", u"Verdes",
    u"Vila", u"Vilas"
    u"Vilar", u"Vilares",

    # Ordinais. Por exemplo, «Cuarta República».
    u"Primeira", u"Primeiras", u"Primeiro", u"Primeiros",
    u"Segunda", u"Segundas", u"Segundo", u"Segundos",
    u"Terceira", u"Terceiras", u"Terceiro", u"Terceiros",
    u"Cuarta", u"Cuartas", u"Cuarto", u"Cuartos",
    u"Quinta", u"Quintas", u"Quinto", u"Quintos",
    u"Sexta", u"Sextas", u"Sexto", u"Sextos",
    u"Sétima", u"Sétimas", u"Sétimo", u"Sétimos",
    u"Oitava", u"Oitavas", u"Oitavo", u"Oitavos",
    u"Novena", u"Novenas", u"Noveno", u"Novenos",
    u"Décima", u"Décimas", u"Décimo", u"Décimos",
)
